# Generated by Django 3.2.3 on 2021-05-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='displaydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('payment_status', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('payment_mode', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('staff_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=30)),
            ],
        ),
    ]
