# Generated by Django 3.2.3 on 2021-05-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_displaydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaydata',
            options={'managed': False},
        ),
    ]
