# Generated by Django 3.2.3 on 2021-05-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_displaydata_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='displaydata',
            table='displaydata',
        ),
    ]
