# Generated by Django 3.2.3 on 2021-05-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_displaydata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.FloatField()),
                ('payment_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.FloatField()),
                ('payment_status', models.CharField(max_length=10)),
                ('payment_mode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StaffList',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('no_absent_days', models.IntegerField()),
                ('salary', models.FloatField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='displaydata',
        ),
    ]
