# Generated by Django 3.2.3 on 2021-05-31 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_stafflist_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffList',
        ),
    ]
