# Generated by Django 3.2.3 on 2021-05-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_stafflist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffList',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('no_absent_days', models.IntegerField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
